name: tempus
description: Handy tools for parsing, manipulating and displaying DateTimes in Dart.
version: 0.4.1
homepage: https://github.com/Avyiel/tempus

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  intl: "^0.16.0"

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.9.4