name: tempus
description: Handy tools for parsing, manipulating and displaying DateTimes in Dart.
version: 0.3.1
author: Lucas Vienna <dev@lucasvienna.dev>
homepage: https://github.com/Avyiel/tempus

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  intl: "^0.15.0"

dev_dependencies:
  test: "^1.5.0"