name: tempus
description: Handy tools for parsing, manipulating and displaying DateTimes in Dart.
version: 1.0.0
homepage: https://github.com/Avyiel/tempus
repository: https://github.com/Avyiel/tempus
issue_tracker: https://github.com/Avyiel/tempus/issues

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  intl: "^0.16.0"

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.9.4
