name: better_moment
description: A port of the Moment.js library for easy time manipulation in Dart.
version: 0.1.0
author: Avyiel <lmvienna@outlook.com>
homepage: https://github.com/Avyiel/better_moment

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

# dependencies:
#   meta: ^1.1.6

dev_dependencies:
  test: "^1.5.0"
